version: '3'
services:
  podsearch:
    build: .
    ports:
      - "8080:8080"
    environment:
      - "ALGOLIAID="
      - "ALGOLIAKEY="
      - "PPORT=26257"
      - "PHOST=db"
      - "ELASTICHOST=search"
      - "ELASTICUSER=elastic"
      - "ELASTICPASS=changeme"
      - "PUSER=root"
    command: ["podsearch","-env", "-wait"]
    depends_on:
      - db
      - search
     
  db:
    image: cockroachdb/cockroach:v1.0.4
    ports:
      - "127.0.0.1:8000:8080"
    command: start --insecure
  
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    environment:
    - "http.host=0.0.0.0"
    - "transport.host=127.0.0.1"